# Basic settings
title:            "不忘初心"
description:      "于子杰和自己的对话。"
baseurl:          "" # Subpath of your site
url:              "http://yuzijie.com" # Site url.
twitter_username: "yuzijie"
github_username:  "yuzijie"
email:            blog@yuz.me
author:           "Zac YU"

# Build settings
markdown: kramdown

# Sass
sass:
  style: compressed

# Navigation
links:
  - name:         最近更新
    url:          /

  - name:         话题分类
    url:          /topics

  - name:         关于本站
    url:          /about

  # - name:         链接收集
  #   url:          /links

  # - name:         Email
  #   url:          mailto:blog@yuz.me
  #   external:     true

  # - name:         GitHub
  #   url:          http://github.com/yuzijie
  #   external:     true

# Scopes
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      is_post: true
