# Site settings
name: "Zac"
title: "不忘初心"
email: blog@yuz.me
description: > # this means to ignore newlines until "baseurl:"
  于子杰与自己的对话。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yuzijie.com" # the base hostname & protocol for your site
twitter_username: yuzijie
github_username:  yuzijie

# Build settings
markdown: kramdown

# Sass
sass:
  style: compressed

# Navigation
nav:
  - name: "yuz.me"
    href: "//yuz.me"

# Scopes
# defaults:
#   -
#     scope:
#       path: ""
#       type: "pages"
#     values:
#       layout: "page"
#   -
#     scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: "post"
